const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const path='../assets/js/ai100/fish-linear-fit.js';
function fresh(){delete require.cache[require.resolve(path)];return require(path);}
test('activity uses real CSV rows with disjoint 127/32 split',()=>{const a=fresh();const csv=fs.readFileSync('ai100/data/Fish.csv','utf8').trim().split(/\r?\n/).slice(1).map(l=>{const [id,,y,x]=l.split(',');return {id:+id,x:+x,y:+y};});assert.equal(a.training.length,127);assert.equal(a.test.length,32);assert.equal(new Set([...a.training,...a.test].map(p=>p.id)).size,159);for(const p of [...a.training,...a.test])assert.deepEqual(p,csv.find(r=>r.id===p.id));});
test('least squares matches a known solution and minimizes real-data squared error',()=>{const a=fresh();assert.deepEqual(a.fit([{x:0,y:3},{x:1,y:5},{x:2,y:7}]),{slope:2,intercept:3});assert.equal(a.error([{x:2,y:7}],2,3),0);const {slope,intercept}=a.optimum,best=a.error(a.training,slope,intercept);assert.ok(best<a.error(a.training,8,150));for(const [ds,di] of [[1,0],[-1,0],[0,10],[0,-10],[1,-10]])assert.ok(best<a.error(a.training,slope+ds,intercept+di));const residuals=a.training.map(p=>p.y-slope*p.x-intercept);assert.ok(Math.abs(residuals.reduce((s,x)=>s+x,0))<1e-6);});
function fixture(reduced=false){const a=fresh(),map=new Map(),frames=new Map();let id=0;function el(){return {value:'',textContent:'',attrs:{},isConnected:true,classList:{toggle(){}},setAttribute(k,v){this.attrs[k]=v;},focus(){this.focused=true;}};}const dots=a.training.map(el),errors=a.training.map(el);const card={isConnected:true,querySelector(s){if(!map.has(s))map.set(s,el());return map.get(s);},querySelectorAll(s){return s==='[data-fish]'?dots:errors;}};global.requestAnimationFrame=fn=>{frames.set(++id,fn);return id;};global.cancelAnimationFrame=n=>frames.delete(n);global.matchMedia=()=>({matches:reduced});a.bind({querySelector:()=>card});function tick(t){const work=[...frames.values()];frames.clear();work.forEach(fn=>fn(t));}return {a,q:s=>card.querySelector(s),dots,card,tick,frames};}
test('guided steps enable the intended controls, give real feedback, and reset',()=>{const f=fixture();assert.equal(f.q('[data-fit-slope]').disabled,false);assert.equal(f.q('[data-fit-intercept]').disabled,true);f.q('[data-fit-slope]').value=9;f.q('[data-fit-slope]').oninput();assert.equal(f.q('[data-fit-status]').textContent,'Closer fit.');f.q('[data-fit-slope]').value=8;f.q('[data-fit-slope]').oninput();assert.equal(f.q('[data-fit-status]').textContent,'Try the other direction.');f.q('[data-fit-next]').onclick();assert.equal(f.q('[data-fit-slope]').disabled,true);assert.equal(f.q('[data-fit-intercept]').disabled,false);assert.ok(f.q('[data-fit-intercept]').focused);f.q('[data-fit-next]').onclick();assert.equal(f.q('[data-fit-slope]').disabled,false);assert.equal(f.q('[data-fit-intercept]').disabled,false);f.q('[data-fit-next]').onclick();assert.equal(f.q('[data-fit-next]').hidden,true);assert.equal(f.q('[data-fit-best]').textContent,'Apply Best Fit');f.q('[data-fit-reset]').onclick();assert.equal(+f.q('[data-fit-slope]').value,8);assert.equal(+f.q('[data-fit-intercept]').value,-500);assert.equal(f.q('[data-fit-next]').hidden,false);assert.equal(f.q('[data-fit-step]').textContent,'STEP 1 OF 4');});
test('feedback tooltip only shows while an enabled slider is held and clears on release/cancel',()=>{const f=fixture(),slider=f.q('[data-fit-slope]'),tip=f.q('[data-fit-tooltip]');slider.setPointerCapture=()=>{};assert.equal(tip.hidden,true);slider.onpointerdown({button:0,pointerId:1});assert.equal(tip.hidden,false);slider.value=9;slider.oninput();assert.equal(tip.textContent,'Closer fit.');slider.onpointerup();assert.equal(tip.hidden,true);slider.value=10;slider.oninput();assert.equal(tip.hidden,true);slider.onpointerdown({button:0,pointerId:2});slider.onpointercancel();assert.equal(tip.hidden,true);slider.onpointerdown({button:0,pointerId:3});slider.onlostpointercapture();assert.equal(tip.hidden,true);f.q('[data-fit-intercept]').onpointerdown({button:0,pointerId:4});assert.equal(tip.hidden,true);});

test('Compare preserves student line; Apply animates to optimum; reset clears overlay',()=>{const f=fixture();f.q('[data-fit-next]').onclick();f.q('[data-fit-next]').onclick();const before=f.q('[data-fit-line]').attrs.y2;f.q('[data-fit-next]').onclick();assert.equal(f.frames.size,0);assert.equal(f.q('[data-fit-line]').attrs.y2,before);assert.equal(f.q('[data-fit-ideal]').attrs.visibility,'visible');assert.equal(f.q('[data-fit-best]').textContent,'Apply Best Fit');f.q('[data-fit-best]').onclick();f.tick(0);f.tick(700);assert.equal(+f.q('[data-fit-slope]').value,f.a.optimum.slope);assert.equal(+f.q('[data-fit-intercept]').value,f.a.optimum.intercept);f.q('[data-fit-reset]').onclick();assert.equal(f.q('[data-fit-ideal]').attrs.visibility,'hidden');assert.equal(f.q('[data-fit-best]').disabled,false);assert.equal(+f.q('[data-fit-slope]').value,8);});
test('skip opens comparison first; reduced motion applies immediately; reset cancels animation',()=>{const f=fixture(true);f.q('[data-fit-best]').onclick();assert.equal(+f.q('[data-fit-slope]').value,8);assert.equal(f.frames.size,0);f.q('[data-fit-best]').onclick();f.tick(0);assert.equal(+f.q('[data-fit-slope]').value,f.a.optimum.slope);assert.equal(f.frames.size,0);f.q('[data-fit-reset]').onclick();f.q('[data-fit-best]').onclick();f.q('[data-fit-best]').onclick();f.q('[data-fit-reset]').onclick();assert.equal(f.frames.size,0);});
test('fit summary appears only after applying finishes and clears on reset',()=>{const f=fixture(),summary=f.q('[data-fit-summary]');assert.equal(summary.hidden,true);f.q('[data-fit-best]').onclick();assert.equal(summary.hidden,true);f.q('[data-fit-best]').onclick();f.tick(0);assert.equal(summary.hidden,true);f.tick(700);assert.equal(summary.hidden,false);f.q('[data-fit-reset]').onclick();assert.equal(summary.hidden,true);});
