const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('assets/js/components/ai-ml-lab.js','utf8');
function fixture(explore={},name="data-detective"){const ctx={window:{},state:{explore},store(){}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('assets/js/ai100/'+name+'-config.js','utf8'),ctx);ctx.C=ctx.window.ML_LAB_CONFIG;vm.runInContext(source.slice(source.indexOf('function guidedExploreState(){'),source.indexOf('function guidedHistogram(')),ctx);return ctx;}
test('only checking a selected response increments attempts and unlocks a correct response',()=>{const c=fixture(),x=c.guidedExploreState(),id=c.C.explore.tasks[0].id;x.justifications[id]='Pandas loads the CSV into a table.';assert.equal(c.checkReviewResponse(0),false);assert.equal(x.attempts[id],undefined);c.selectReviewResponse(0,1);assert.equal(x.attempts[id],undefined);assert.equal(x.answers[id],undefined);c.checkReviewResponse(0);assert.equal(x.attempts[id],1);assert.equal(c.guidedTaskComplete(0),false);c.selectReviewResponse(0,0);assert.equal(x.attempts[id],1);assert.equal(c.guidedTaskComplete(0),false);c.checkReviewResponse(0);assert.equal(x.attempts[id],2);assert.equal(c.guidedTaskComplete(0),true);assert.equal(x.unlocked,1);const restored=fixture(JSON.parse(JSON.stringify(x)));assert.equal(restored.guidedExploreState().attempts[id],2);assert.equal(restored.guidedTaskComplete(0),true);restored.checkReviewResponse(0);assert.equal(restored.state.explore.attempts[id],3);});
test('legacy saved answers remain valid without invented attempt counts',()=>{const c=fixture({questionOrder:2,answers:{'loading-library':0},completed:[0],justifications:{'loading-library':'Pandas loads the CSV into a table.'}}),x=c.guidedExploreState();assert.equal(x.attempts['loading-library'],undefined);assert.equal(c.guidedTaskComplete(0),true);assert.equal(x.drafts['loading-library'],0);});

for(const name of ['data-detective','fish-predictor','hidden-patterns','loan-auditor'])test(name+' requires explicit checking and explanation and retains attempts',()=>{
 const c=fixture({},name),x=c.guidedExploreState(),t=c.C.explore.tasks[0],wrong=(t.correct+1)%t.options.length;
 assert.equal(c.checkReviewResponse(0),false);c.selectReviewResponse(0,wrong);assert.equal(x.attempts[t.id],undefined);c.checkReviewResponse(0);assert.equal(x.attempts[t.id],1);assert.equal(c.guidedTaskComplete(0),false);
 c.selectReviewResponse(0,t.correct);assert.equal(x.answers[t.id],undefined);assert.equal(x.attempts[t.id],1);c.checkReviewResponse(0);assert.equal(c.guidedTaskComplete(0),false);
 x.justifications[t.id]='This explanation supports the answer using the evidence shown.';c.updateGuidedCompletion(0);assert.equal(c.guidedTaskComplete(0),true);
 const restored=fixture(JSON.parse(JSON.stringify(x)),name);assert.equal(restored.guidedExploreState().attempts[t.id],2);assert.equal(restored.guidedTaskComplete(0),true);
 const old=JSON.parse(JSON.stringify(x));delete old.attempts;delete old.drafts;const legacy=fixture(old,name),saved=legacy.guidedExploreState();assert.equal(saved.attempts[t.id],undefined);assert.equal(saved.drafts[t.id],t.correct);assert.equal(legacy.guidedTaskComplete(0),true);
});
